package com.fng.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.ID
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TITLE
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMTCREATE
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private Long gmtcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.GMTMODIFIED
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private Long gmtmodified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.CREATOR
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.COMMITCOUNT
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private Integer commitcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.VIEWCOUNT
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private Integer viewcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.LIKECOUNT
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private Integer likecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.TAG
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QUESTION.DESCRIPTION
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.ID
     *
     * @return the value of QUESTION.ID
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.ID
     *
     * @param id the value for QUESTION.ID
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.TITLE
     *
     * @return the value of QUESTION.TITLE
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.TITLE
     *
     * @param title the value for QUESTION.TITLE
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.GMTCREATE
     *
     * @return the value of QUESTION.GMTCREATE
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public Long getGmtcreate() {
        return gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.GMTCREATE
     *
     * @param gmtcreate the value for QUESTION.GMTCREATE
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setGmtcreate(Long gmtcreate) {
        this.gmtcreate = gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.GMTMODIFIED
     *
     * @return the value of QUESTION.GMTMODIFIED
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public Long getGmtmodified() {
        return gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.GMTMODIFIED
     *
     * @param gmtmodified the value for QUESTION.GMTMODIFIED
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setGmtmodified(Long gmtmodified) {
        this.gmtmodified = gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.CREATOR
     *
     * @return the value of QUESTION.CREATOR
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.CREATOR
     *
     * @param creator the value for QUESTION.CREATOR
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.COMMITCOUNT
     *
     * @return the value of QUESTION.COMMITCOUNT
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public Integer getCommitcount() {
        return commitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.COMMITCOUNT
     *
     * @param commitcount the value for QUESTION.COMMITCOUNT
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setCommitcount(Integer commitcount) {
        this.commitcount = commitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.VIEWCOUNT
     *
     * @return the value of QUESTION.VIEWCOUNT
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public Integer getViewcount() {
        return viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.VIEWCOUNT
     *
     * @param viewcount the value for QUESTION.VIEWCOUNT
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setViewcount(Integer viewcount) {
        this.viewcount = viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.LIKECOUNT
     *
     * @return the value of QUESTION.LIKECOUNT
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public Integer getLikecount() {
        return likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.LIKECOUNT
     *
     * @param likecount the value for QUESTION.LIKECOUNT
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setLikecount(Integer likecount) {
        this.likecount = likecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.TAG
     *
     * @return the value of QUESTION.TAG
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.TAG
     *
     * @param tag the value for QUESTION.TAG
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QUESTION.DESCRIPTION
     *
     * @return the value of QUESTION.DESCRIPTION
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QUESTION.DESCRIPTION
     *
     * @param description the value for QUESTION.DESCRIPTION
     *
     * @mbg.generated Tue Feb 18 21:35:20 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}